trigger:
  - main

pr: none

resources:
  pipelines:
  - pipeline: upstream_ess_master
    project: ess
    source: Main
    trigger: true

variables:
  is_release: false

stages:
  - stage: 'notebook_tests'
    displayName: 'notebook tests'

    jobs:
      - template: test_notebooks.yml
  - stage: 'make_sphinx_documentation'
    displayName: 'make sphinx documentation'

    jobs:
      - template: documentation_build.yml
  - stage: "deploy_documentation"
    displayName: "deploy documentation"

    jobs:
      - template: documentation_deploy.yml
