trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

variables:
  is_release: $[eq(variables['System.PullRequest.TargetBranch'], 'release')]
  target_branch: $[variables['System.PullRequest.TargetBranch']]

stages:
  - stage: 'make_sphinx_documentation'
      displayName: 'make sphinx documentation'

      jobs:
        - template: documentation_build.yml
