parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: with_scippbuildtools

trigger:
  branches:
    exclude:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: pipelines/stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    gh_pages_subdirectory: 'ess-notebooks'
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'ess-notebooks.yml'
    build_package: false
