parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  tags:
    include:
      - '*.*.*'

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp'
    gh_pages_subdirectory: 'ess-notebooks'
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'ess-notebooks.yml'
    deploy: true
    build_package: false
    release: true
